-- 1) List all customers who have made purchases of more than $80.

SELECT 
    U.name, 
    U.email, 
    SUM(O.total_amount) AS total_spent
FROM 
    Users U
JOIN 
    Orders O ON U.user_id = O.user_id
GROUP BY 
    U.user_id
HAVING 
    total_spent > 80;
 -- 2)Retrieve all orders placed in the last 280 days along with the customer name and email.
 SELECT
 U.name,
 U.email,
 o.order_id,
 o.order_date,
 o.total_amount
 FROM
 Users u
 JOIN
 Orders O ON U.user_id = O.user_id
 WHERE 
    O.order_date >= CURDATE() - INTERVAL 280 DAY
ORDER BY 
    O.order_date DESC;
-- 3)Find the average product price for each category.
SELECT category,
AVG(price) AS average_price
FROM products
GROUP BY category;

-- 4) List all customers who have purchased a product from the category Electronics.
 SELECT DISTINCT 
 U.user_id, U.name, U.email
 FROM Users U
 JOIN
 Orders O ON U.user_id = o.user_id
 JOIN 
 OrderDetails OD ON o.order_id=OD.order_id
 JOIN
 Products P ON OD.product_id = P.product_id
 WHERE
 P.category ='Electronics';
 
 -- 5)Find the total number of products sold and the total revenue generated for each product.
 SELECT
 P.product_id,
 P.name AS product_name,
 SUM(OD.quantity) As total_quantity_sold,
 SUM(OD.quantity * P.price) AS total_revene
 FROM
 Products P
 JOIN
 OderDetails OD ON P. product_id = OD.product_id
 GROUP BY
 P.product_id,P.name;
 -- 6)Update the price of all products in the Books category, increasing it by 10%.
 UPDATE products
 SET price =price * 1.10
 WHERE category = 'Books';
 
 -- 7) Remove all orders that were placed before 2020
 DELETE  FROM orders
 WHERE order_date < '2020-01-01';
 -- 8) Write a query to fetch the order details, including customer name, product name, and 
-- quantity, for orders placed on 2024-05-01.
SELECT
U.name AS customer_name,
P.name AS product_name,
OD.quantity
FROM 
Users U
JOIN
Orders O ON U.user_id = O.user_id
JOIN
OrderDetails OD ON O.order_id = OD.order_id
JOIN
Products P ON OD.product_id = P.product_id
WHERE
O.order_date = '2024-05-01';
 -- 9) Fetch all customers and the total number of orders they have placed
 SELECT
 U.user_id,
 U.name AS customer_name,
 count(o.order_id) AS total_orders
 FROM
 Users U
 LEFT JOIN
 Orders O ON U_user_id = O.user_id
 GROUP BY
 U.user_id, U.name;
 
 -- 10)  Retrieve the average rating for all products in the Electronics category.
 SELECT 
    P.name AS product_name,
    AVG(R.rating) AS average_rating
FROM 
    Products P
JOIN 
    Ratings R ON P.product_id = R.product_id
WHERE 
    P.category = 'Electronics'
GROUP BY 
    P.product_id, P.name;               
 -- 11) List all customers who purchased more than 1 units of any product, including the product 
-- name and total quantity purchased.
 SELECT 
    U.user_id,
    U.name AS customer_name,
    P.name AS product_name,
    SUM(OD.quantity) AS total_quantity
FROM 
    Users U
JOIN 
    Orders O ON U.user_id = O.user_id
JOIN 
    OrderDetails OD ON O.order_id = OD.order_id
JOIN 
    Products P ON OD.product_id = P.product_id
GROUP BY 
    U.user_id, U.name, P.product_id, P.name
HAVING 
    SUM(OD.quantity) > 1;
 
 -- 12)  Find the total revenue generated by each category along with the category name
 SELECT
 P.category,
 SUM(OD.quantity * P.price) AS total_revenue
 FROM Products P
 JOIN
 OrderDetails OD ON P.product_id = OD. product_id
 GROUP BY
 P.category;
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 Update the price of all products in the Books category, increasing it by 10%.
 Query. 
Remove all orders that were placed before 2020.
 Write a query to fetch the order details, including customer name, product name, and 
quantity, for orders placed on 2024-05-01.
 Fetch all customers and the total number of orders they have placed.
 Retrieve the average rating for all products in the Electronics category.
 List all customers who purchased more than 1 units of any product, including the product 
name and total quantity purchased.
 Find the total revenue generated by each category along with the category name